### ISSUE TITLE
preview differences in different langs

### ISSUE THREAD

**Issue by VladimirAlexiev** [wetneb/openrefine-wikibase#107] opened 2021-04-22 08:24 UTC
Compare these:
- https://wikidata.reconci.link/en/preview?id=Q917570
- https://wikidata.reconci.link/bg/preview?id=Q917570

`en` is poorer than `bg` (I'm used to `bg` being poorer than `en` for many IT services, but I am not used to the opposite ;-)
![image](https://user-images.githubusercontent.com/536250/115681614-6105fb00-a35d-11eb-8621-3f14cd7aea06.png)
- bg has links on nationality/occupation, en doesn't
- bg has gender, en doesn't
- bg has an award/honor (spelled in French: "commandeur"), en doesn't
- bg has nationality "USA", en has "British-Canadian"
- the list of occupations is different

AHA! I think I know what's going on
- en is the manually-entered description
- bg is the auto-generated description

In contrast, Reasonator https://reasonator.toolforge.org/?q=Q917570 shows both:
![image](https://user-images.githubusercontent.com/536250/115681383-269c5e00-a35d-11eb-8282-eaa237853440.png)

Please show both descriptions in WD preview

**Comment by wetneb** [comment] 2021-04-22 10:50
generally the previews are pretty bad, we should show much more information there. PRs in this direction would be welcome :)

**Comment by wetneb** [comment] 2022-11-10 19:35
duplicate of #123

**Closed by wetneb** 2022-11-10 19:35 UTC
