### ISSUE TITLE
improve Suggest Type

### ISSUE THREAD

**Issue by VladimirAlexiev** [wetneb/openrefine-wikibase#94] opened 2020-10-22 07:43 UTC
https://reconciliation-api.github.io/testbench/ > test bench> Suggest > Class:

Returns all kinds of items not just classes.

Please filter to classes only, i.e. `[] wdt:P31|wdt:P279 ?c`

**Comment by wetneb** [comment] 2020-10-22 12:04
As far as I know there is no formal requirement that things used as values for P31 have a P279 statement on them. So I would be worried that we could forbid legitimate types if we returned only suggestions that have a P279 statement.

One thing that could potentially work is re-rank the suggestions to boost those which have a P279 statement (list them first).

It is also a bit expensive to do this filtering or reordering (since it is not supported by the wbsearchentities API in the first place), we need to fetch the item contents to filter them out.

Feel free to open a PR if you can think of another approach.

**Comment by thadguidry** [comment] 2020-10-22 12:51
@wetneb I think you can instead use SPARQL to handle the filtering and combine it with the wbsearchentities index as I do in some applications?  Here is the thread from David Causse and I that explains how:  https://lists.wikimedia.org/pipermail/wikidata/2020-August/014192.html

**Comment by wetneb** [comment] 2020-10-22 13:06
The problem is that auto-complete requests are fired very often and need to respond quickly, so I would not generate a SPARQL request every time the user does a few keystrokes - that is likely to be too slow and not very kind to the service.

**Comment by VladimirAlexiev** [comment] 2020-10-23 09:16
by `wdt:P31|wdt:P279` I mean "used either as type or as superclass", which is the way WD defines which items are "classes".

**Comment by wetneb** [comment] 2020-10-23 10:14
Right, that makes the criterion even harder to check since it cannot be decided just by looking at the statements on the corresponding items (SPARQL is necessary).

**Comment by thadguidry** [comment] 2020-10-23 15:15
@wetneb What's the link that @VladimirAlexiev is talking about in the issue?  I don't see Suggest Class on the testbench. What am I missing?

**Comment by wetneb** [comment] 2020-10-23 15:17
That's suggest *types*

**Comment by thadguidry** [comment] 2020-10-23 15:26
And there's not already a WD API that can return just Type information?  (give me the P31 or P279)  If not then that sucks, and should be made available. (Freebase had that since it had the direct notion of objects, facts, types, and properties and not just items and statements as Wikidata's data model has [but for good reason](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/44818.pdf), allowing source and reference statements on anything even Types, which is something impossible to do on Freebase)

Hmm, How does Magnus Reasonator hold onto the P31 and P279 on the hover?
![image](https://user-images.githubusercontent.com/986438/97022742-1d4f4780-151a-11eb-93db-a3e1ac2a0f00.png)

**Comment by VladimirAlexiev** [comment] 2020-10-23 18:24
Maybe WD doesn't have such API since it doesn't need it
- there is search "property:SOMETHING" but no "class:SOMETHING"
- the set if classes and hierarchy is completely open. So as I edit an item, I can say "instance of: WHATEVER" and right then WHATEVER becomes a class

**Comment by wetneb** [comment] 2022-11-10 19:27
No way to do this filtering efficiently, so closing.

**Closed by wetneb** 2022-11-10 19:27 UTC
