### ISSUE TITLE
Occasional error messages in hover popup for Wikidata reconciliation suggestions

### ISSUE THREAD

**Issue by trnstlntk** [wetneb/openrefine-wikibase#136] opened 2022-04-29 21:13 UTC
Maybe this is a similar issue as #105 or (in the OpenRefine issue tracker) [4715](https://github.com/OpenRefine/OpenRefine/issues/4715).

This is not easy to reproduce; this behavior occurs at random moments (but I see it a lot, usually at least a few times for each Wikidata-reconciled dataset I'm working with in OpenRefine).

Sometimes the blue popup dialog that appears when hovering over a reconciliation suggestion hesitates a bit, and then refuses to display the suggested (existing!) entity's image + short info (label + description or auto-description). Rather, an error message of the following form will appear:

`{"arguments":{"id":"Q27616211","lang":"en"},"details":"","message":"invalid query","status":"error"}`

Here I caught it in action...
![image](https://user-images.githubusercontent.com/9881645/166068749-5ef46e92-e0e2-4b4f-83ae-6678a8ac7ae3.png)

And then, just two minutes later all is well again... 
![image](https://user-images.githubusercontent.com/9881645/166068801-ec8dec8b-63c9-4533-b5b6-408394cb1abb.png)

**Comment by wetneb** [comment] 2022-11-10 19:55
Duplicate of #105

**Closed by wetneb** 2022-11-10 19:55 UTC
